# Generated by Django 2.2.5 on 2019-12-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimono', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='firstname',
        ),
    ]
