# Generated by Django 2.2.5 on 2019-12-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimono', '0002_auto_20191217_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='firstname',
            new_name='message',
        ),
    ]
