# Generated by Django 2.2.5 on 2019-12-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimono', '0003_auto_20191217_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lastname',
            field=models.CharField(default=999, max_length=255),
            preserve_default=False,
        ),
    ]
